version: 2

builds:
  - id: ec2-ssh
    binary: ec2-ssh
    main: ./cmd/ec2-ssh
    goos:
      - linux
      - darwin
      - windows

brews:
  - repository:
      owner: mrtimp
      name: homebrew-formulas
    directory: Formula
    homepage: "https://github.com/mrtimp/aws-ec2-ssh"
    description: "SSH helper for connecting to EC2 instances via EC2 Instance Connect"
    commit_author:
      name: mrtimp
      email: timp@unfuddle.nz
